# Generated by Django 2.1.2 on 2018-11-21 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181118_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='last_updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
